apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bancswissunique-bancswissunique-poi-map-app-dev
  annotations:
    argocd/app-name: bancswissunique-bancswissunique-poi-map-app-dev
    backstage.io/kubernetes-id: bancswissunique-bancswissunique-poi-map-app-dev
    backstage.io/kubernetes-namespace: bancswissunique
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=bancswissunique-bancswissunique-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus2/bancswissunique-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/dev-pipelines/ns/bancswissunique/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/k8s/ns/bancswissunique/deployments/bancswissunique-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23blues.6mbu.p1.openshiftapps.com/#https://github.com/Summit23Janus2/bancswissunique-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://bancswissunique-poi-map-app-bancswissunique.apps.summit23blues.6mbu.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/bancswissunique"
  system: workshop-system-bancswissunique
  consumesApis:
    - gateway-api-bancswissunique
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-bancswissunique
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/bancswissunique"
